In [1]:
import pandas as pd
import os

In [2]:
path = "./fg/"
file_name = []
for root, dirs, files in os.walk(path):
    for name in files:
        file_name.append(name)
df = pd.DataFrame(file_name, columns=['file_name'])

In [3]:
df.sample()

        file_name
4520  5219138.pkl

In [4]:
pp = path + df.sample().file_name.values[0]
pp

'./fg/5218151.pkl'

In [18]:
tt = pd.DataFrame()
for index, row in df.iterrows():
    file_name = row.file_name
    try:
        pp = path + file_name
        tb = pd.read_pickle(pp)
        description = tb.head(1)['zhengcewenjian.description'].values[0]
        aging = tb.head(1)['zhengcewenjian.aging'].values[0]
        title = tb.head(1).title.values[0]
        content = tb.head(1).content.values[0]
        publishedTimeStr = tb.head(1).publishedTimeStr.values[0]

        dic = {'file_name':file_name, 'description':description, 'aging':aging, 'title':title, 'content':content, 'time':publishedTimeStr.split(' ')[0]}
        tt = pd.concat([tt, pd.DataFrame(dic, index=[0])], ignore_index=True)
    except:
        print(file_name)
        continue

ww.chinatax.gov.cnc5193174.pkl

In [19]:
tt.sample(10)

,file_name,description,aging,title,content,time
4203,5217773.pkl,,,国家税务总局关于中国银联股份有限公司特别风险准备金及风险损失税前扣除问题的通知,各省、自治区、直辖市和计划单列市国家税务局： 为了防范与化解中国银联股份有限公司提供银行卡跨...,2007-03-12
302,5193297.pkl,1.《国家税务总局关于修改部分税收规范性文件的公告》（国家税务总局公告2018年第31号）对...,全文废止,国家税务总局国家质量技术监督局关于加油机安装税控装置和生产使用税控加油机有关问题的通知,改革开放以来，随着我国经济建设和交通运输事业的迅速发展，加油站遍布全国城乡，成品油销售量逐年...,1999-06-04
1813,5195017.pkl,null,全文有效,国家税务总局关于《实施税收协定相关措施以防止税基侵蚀和利润转移的多边公约》对我国生效并对部分...,《实施税收协定相关措施以防止税基侵蚀和利润转移的多边公约》（以下简称《公约》），由经济合作与...,2022-08-01
3811,5213575.pkl,全文废止失效。参见：《国家税务总局关于公布全文失效废止和部分条款废止的税收规范性文件目录的公...,全文废止,国家税务总局关于做好2008年度企业所得税汇算清缴工作的通知,各省、自治区、直辖市和计划单列市国家税务局、地方税务局： 为全面贯彻落实《中华人民共和国企业...,2009-02-06
4722,5221441.pkl,,,工业和信息化部国家发展和改革委员会财政部国家税务总局关于开展2023年度享受研发费用加计扣除...,各省、自治区、直辖市及计划单列市、新疆生产建设兵团工业和信息化主管部门、发展改革主管部门、财...,2024-02-08
4682,5219850.pkl,null,已修改,国家税务总局关于修改《税务登记管理办法》的决定,国家税务总局令第36号 《国家税务总局关于修改〈税务登记管理办法〉的决定》已经2014...,2014-12-27
4075,5217183.pkl,,,国家税务总局关于我国政府和阿曼苏丹国政府避免双重征税和防止偷漏税协定生效及执行的通知,各省、自治区、直辖市和计划单列市国家税务局、地方税务局： 我国政府和阿曼苏丹国政府于2002...,2002-07-02
4503,5219082.pkl,,,国家税务总局关于认真做好小型微利企业所得税优惠政策贯彻落实工作的通知,各省、自治区、直辖市和计划单列市国家税务局、地方税务局: 为认真贯彻落实国务院第102次常务...,2015-09-09
506,5193579.pkl,null,全文有效,国家税务总局关于取消包装物押金逾期期限审批后有关问题的通知,各省、自治区、直辖市和计划单列市国家税务局：根据《国务院关于第三批取消和调整行政审批项目的决...,2004-06-25
2082,5201996.pkl,,,财政部税务总局关于支持居民换购住房有关个人所得税政策的公告,为支持居民改善住房条件，现就有关个人所得税政策公告如下：一、自2022年10月1日至2023...,2022-09-30

In [20]:
tt.aging = tt.aging.astype(str)
tt.time = tt.time.astype(str)

In [21]:
tt.aging.value_counts()

aging
        1576
null    1148
全文有效    1041
全文废止     683
已修改      399
全文失效      27
尚未生效       3
Name: count, dtype: int64

In [24]:
tb = tt[~tt.aging.str.contains('尚未生效|全文失效|已修改|全文废止')].copy()
tb = tb.loc[:, ['title', 'time', 'content']]

In [37]:
tb.sample(10)

,title,time,content
2909,调整化妆品进口环节消费税的通知,2016-09-30,海关总署： 为引导合理消费，经国务院批准，对化妆品的消费税政策进行调整，现将有关问题通知如下...
696,发行2006年版印花税票有关问题的通知,2006-09-30,各省、自治区、直辖市和计划单列市国家税务局、地方税务局：2006年版印花税票已印制完成并开始...
2256,继续实施支持文化企业发展增值税政策的通知,2019-02-13,各省、自治区、直辖市、计划单列市财政厅（局），新疆生产建设兵团财政局，国家税务总局各省、自治...
685,恢复对黄金及其饰品签发出口货物报关单证明联有关问题的通知》的通知,2006-08-22,各省、自治区、直辖市和计划单列市国家税务局：为解决部分出口企业出口含金成分产品无法办理免税手...
1663,印发降低社会保险费率综合方案的通知,2019-04-01,各省、自治区、直辖市人民政府，国务院各部委、各直属机构： 《降低社会保险费率综合方案》已经国...
4109,核定部分车辆最低计税价格有关问题的补充通知,2004-04-13,各省、自治区、直辖市和计划单列市国家税务局、交通厅（局、委），上海、天津市市政管理局： ...
25,1985年国营企业缴纳城市维护建设税有关财务处理的规定,1985-04-10,国务院各部委、局、公司、行，各省、自治区、直辖市财政厅（局）、税务局、建行、分金库，重庆、武...
4650,印发《优化税务执法方式全面推行“三项制度”实施方案》的通知,2019-03-18,国家税务总局各省、自治区、直辖市和计划单列市税务局，国家税务总局驻各地特派员办事处，局内各单...
2767,企业向个人支付不竞争款项征收个人所得税问题的批复,2007-09-12,江苏省财政厅、地方税务局： 江苏省地方税务局《关于外商投资企业购买内资企业资产并向股东个人支...
583,增值税营业税消费税实行先征后返等办法有关城建税和教育费附加政策的通知,2005-05-25,各省、自治区、直辖市、计划单列市财政厅（局）、地方税务局，财政部驻各省、自治区、直辖市、计划...

In [36]:
for index, row in tb.iterrows():
    title = row.title
    if '关于' in title:
        title = title.split('关于')[-1]
    tb.loc[index, 'title'] = title

In [38]:
tb.to_pickle('./tax_law.pkl')

In [ ]:
#第一步关键词搜索
#第二步内容相似度

In [27]:
tb.shape

(3765, 3)

In [29]:
tb[tb.title.str.contains('关于')].shape

(3503, 3)

In [35]:
tb[~tb.title.str.contains('关于')].sample(10)

,title,time,content
1945,纳税担保试行办法,2005-05-24,第一章&ensp;总&ensp;则&ensp;第一条&ensp;为规范纳税担保行为，保障国家...
54,中华人民共和国劳动合同法,2012-12-28,目 录 第一章 总则 第二章 劳动合同的订立 第三章 劳动合同的履行和变更 第四章 劳动合同...
1228,中华人民共和国消费税暂行条例,2008-11-10,第一条 在中华人民共和国境内生产、委托加工和进口本条例规定的消费品的单位和个人，以及国务院确...
2690,中华人民共和国车船税暂行条例实施细则,2007-02-01,《中华人民共和国车船税暂行条例实施细则》经财政部、国家税务总局审议通过，现予公布，自...
4831,法规规章备案审查条例,2024-08-30,第一条 为了规范法规、规章备案审查工作，提高备案审查能力和质量，加强对法规、规章的监督，维护...
3586,第十六批享受优惠政策的企业(集团)技术中心名单、撤销和调整的国家认定企业技术中心名单公告,2009-11-06,根据《国家认定企业技术中心管理办法》，经审定，现将第十六批享受优惠政策的企业(集团)技术中心...
3615,国家经济贸易委员会财政部国家税务总局海关总署公告确认第九批享受优惠政策的企业（集团）技术中心...,2002-12-23,根据国家经贸委、国家税务总局、海关总署《关于印发〈鼓励和支持大型企业和企业集团建立技术中心暂...
5,社会保险基金先行支付暂行办法,2018-12-14,&ensp;&ensp;第一条&ensp;&ensp;为了维护公民的社会保险合法权益，规范社...
3517,免征车辆购置税的新能源汽车车型目录（第十五批）,2017-12-19,为促进我国交通能源战略转型、推进生态文明建设、支持新能源汽车产业发展，根据《财政部国家税务总...
3536,免征车辆购置税的新能源汽车车型目录（第九批）,2016-11-24,&ensp;&ensp;&ensp;&ensp;为促进我国交通能源战略转型、推进生态文明建设...

In [ ]:
tb = pd.read_pickle(pp)
tb.shape

In [ ]:
# tb.head(1).columns.tolist()

In [ ]:
tb.head(1)['zhengcewenjian.description'].values[0]

In [ ]:
tb.head(1)['zhengcewenjian.aging'].values[0]

In [ ]:
tb.head(1).title.values[0]

In [ ]:
tb.head(1).publishedTimeStr.values[0]

In [ ]:
tb.head(1).content.values[0]

In [ ]:
# tb.head(1).values.tolist()